<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="helper/AjaxSetup.css" />
        <style>
            .container {
                border-bottom: 1px dotted #ccc;
                padding-bottom: 20px;
                margin-bottom: 30px;
                display: flex;
            }

            .container a {
                display: block;
                margin-right: 30px;
            }

            .text-success {
                color: #0066ff;
                font-size: 24px;
            }

            .text-primary {
                color: #007700;
                font-size: 24px;
            }
        </style>
    </head>
    <body>
        <h1>Async Await Renawal</h1>
        <div class="container">
            <a href="#" id="btn">Async Await Load</a>
        </div>
        <div id="result"></div>

        <script>
            /** Async Await 방식의 Ajax 요청(권장) */
            document.querySelector("#btn").addEventListener("click", async (e) => {
                e.preventDefault();

                console.log("Loading...");

                // 요청(접속)할 대상 페이지 주소 -> 이 파일의 소스코드를 읽어온다.
                const url = "http://localhost:8080/world.html";

                // 결과를 저장할 변수
                let result = null;

                try {
                    const response = await fetch(url);

                    // 백엔드가 에러를 보내왔다면?
                    if (response.status != 200) {
                        // 에러 객체 생성후 에러 발생 --> catch로 이동함
                        const err = new Error(response.statusText);
                        err.status = response.status;
                        throw err;
                    }

                    result = await response.text();
                } catch (error) {
                    // 백엔드에게 접속 조차 못해보는 경우 (네트워크 문제)
                    console.error(error);
                    alert(error.message);
                    // catch에서 return을 하더라도 finally가 수행된 후 실행이 취소된다.
                    return;
                } finally {
                    console.log("Finish!!!");
                }

                // 정상적인 응답을 받아온 경우 --> 응답 결과를 화면에 출력한다.
                document.querySelector("#result").innerHTML += result;
            });
        </script>
    </body>
</html>
